version: 2

sources:
  - name: LakehouseAs400
    description: "Source tables from AS400 system"
    database: elysium_dev
    schema: LakehouseAs400
    tables:
      - name: PROD_membership_cards
        description: "Raw membership cards data from AS400"
        columns:
          - name: Cost_Center
            description: "Cost center identifier"
          - name: Account_Number
            description: "Account number"
          - name: Card_Number
            description: "Card number"
              
      - name: PROD_membership_accounts
        description: "Raw membership accounts data from AS400"
        columns:
          - name: Cost_Center
            description: "Cost center identifier"
          - name: Account_Number
            description: "Account number"
              
      - name: PROD_membership_transactions_header
        description: "Raw membership transactions data from AS400"
        columns:
          - name: Cost_Center
            description: "Cost center identifier"
          - name: Account_Number
            description: "Account number"
          - name: Transaction_Date
            description: "Transaction date"
              
      - name: PROD_clubs
        description: "Raw clubs data from AS400"
        columns:
          - name: Club_Number
            description: "Club number identifier"
          - name: Club_Name
            description: "Club name"
              
      - name: PROD_dates
        description: "Raw dates data for date dimension"
        columns:
          - name: Date
            description: "Date value"
